name: userop
description: A lightweight Dart library for quickly and easily building ERC-4337
  UserOperations.
version: 0.2.0
repository: https://github.com/fuseio/userop.dart

environment:
  sdk: ^3.0.5

dependencies:
  eth_sig_util: ^0.0.9
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  stream_channel: ^2.1.2
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
  web3dart_builders: ^0.0.7
