name: userop
description: A lightweight Dart library for quickly and easily building ERC-4337
  UserOperations.
version: 0.1.3
repository: https://github.com/fuseio/userop.dart

environment:
  sdk: ^3.0.5

dependencies:
  eth_sig_util: ^0.0.9
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  json_annotation: ^4.8.1
  web3dart: ^2.7.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.1
  web3dart_builders: ^0.0.7
