name: userop
description: A simple Dart library for building ERC-4337 UserOperations.
version: 0.0.3
repository: https://github.com/fuseio/userop.dart

environment:
  sdk: ^3.0.5

dependencies:
  decimal: ^2.3.3
  dio: ^5.3.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  test: ^1.24.5
  web3dart: ^2.7.1

dev_dependencies:
  build_runner: ^2.4.6
  faker_dart: ^0.2.1
  freezed: ^2.4.1
  web3dart_builders: ^0.0.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
